language: scala
scala:
  - 2.12.8
script:
  - sbt clean coverage test coverageReport &&
    sbt coverageAggregate
after_success:
  - sbt coveralls &&
    sbt -Dbintray.user=${BINTRAY_USERNAME} -Dbintray.pass=${BINTRAY_PASSWORD}
sudo: false